<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class EmailVariableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $emailVariables = [
            ['ACCIDENT_SPECIAL_NOTES', '', '', ''],
            ['ADDRESS_OF_ACCIDENT', '', '', ''],
            ['ADJUSTER_EMAIL', '', '', ''],
            ['ADJUSTER_PHONE_NUMBER', '', '', ''],
            ['ALT_PHONE_NUMBER', '', '', ''],
            ['ALT_PHONE_NUMBER_2', '', '', ''],
            ['ALT_PHONE_NUMBER_2_NAME', '', '', ''],
            ['ALT_PHONE_NUMBER_NAME', '', '', ''],
            ['ANSWER_FIELD', '', '', ''],
            ['ANSWER_SERVED', '', '', ''],
            ['AP_CASE_FILED', '', '', ''],
            ['AP_CASE_NO', '', '', ''],
            ['AP_RESPONSE_DUE', '', '', ''],
            ['AP_STATUS', '', '', ''],
            ['ATTORNEY_ADDRESS', '', '', ''],
            ['ATTORNEY_CITY_STATE_ZIP', '', '', ''],
            ['ATTORNEY_EMAIL', '', '', ''],
            ['ATTORNEY_ID', '', '', ''],
            ['ATTORNEY_NAME', '', '', ''],
            ['ATTORNEY_PHONE_NUMBER', '', '', ''],
            ['ATTORNEY_SUITE', '', '', ''],
            ['BALANCE', '', '', ''],
            ['CASETYPE_DESCRIPTION', '', '', ''],
            ['CASETYPE_ID', '', '', ''],
            ['CASE_CLOSED', '', '', ''],
            ['CASE_CLOSED_DATE', '', '', ''],
            ['CASE_FILED', '', '', ''],
            ['CASE_NUMBER', '', '', ''],
            ['CASE_STATUS_DESCRIPTION', '', '', ''],
            ['CASE_STATUS_ID', '', '', ''],
            ['CASE_TITLE', '', '', ''],
            ['CC1', '', '', ''],
            ['CC2', '', '', ''],
            ['CHAPTER_DESCRIPTION', '', '', ''],
            ['CHAPTER_ID', '', '', ''],
            ['CLIENT_INS_COMPANY_NAME', '', '', ''],
            ['CLIENT_NAME', '', '', ''],
            ['CLIENT_PHONE_NUMBER', '', '', ''],
            ['CODE', '', '', ''],
            ['COMPLAINT_FILED', '', '', ''],
            ['COMPLAINT_SERVED', '', '', ''],
            ['CONFIRMATION_HEARING_DATE', '', '', ''],
            ['CONFIRMATION_HEARING_DESCRIPTION', '', '', ''],
            ['CONFIRMATION_HEARING_ID', '', '', ''],
            ['CONFIRMATION_HEARING_ROOM', '', '', ''],
            ['CONFIRMATION_HEARING_TIME', '', '', ''],
            ['CONSULTANT', '', '', ''],
            ['CONTACT_NAME', '', '', ''],
            ['CONT_HEARING_DATE', '', '', ''],
            ['CONT_HEARING_LOCATION', '', '', ''],
            ['CONT_HEARING_NOTES', '', '', ''],
            ['CONT_HEARING_TIME', '', '', ''],
            ['COURT_ADDRESS', '', '', ''],
            ['DATE_OF_LOSS', '', '', ''],
            ['DATE_OF_TRIAL', '', '', ''],
            ['DEFENDANT_ADDRESS', '', '', ''],
            ['DEFENDANT_NAME', '', '', ''],
            ['DEFENDANT_PHONE_NUMBER', '', '', ''],
            ['DEPARTMENT', '', '', ''],
            ['DE_FILED', '', '', ''],
            ['DISCOVER_CUTOFF', '', '', ''],
            ['DOB', '', '', ''],
            ['DRIVER_LICENSE_NO', '', '', ''],
            ['EMAIL_1', '', '', ''],
            ['EMAIL_2', '', '', ''],
            ['FILE_LOCATION', '', '', ''],
            ['FILE_NUMBER', '', '', ''],
            ['FILE_NUMBER_2', '', '', ''],
            ['FILING_DATE', '', '', ''],
            ['FIRST_DOWN_PAYMENT', '', '', ''],
            ['IMPACT', '', '', ''],
            ['JUDGE', '', '', ''],
            ['JUDGE_ADDRESS', '', '', ''],
            ['JUDGE_CITY_STATE_ZIP', '', '', ''],
            ['JUDGE_ID', '', '', ''],
            ['JUDGE_NAME', '', '', ''],
            ['JUDGE_PHONE_NUMBER', '', '', ''],
            ['JUDGE_ROOM', '', '', ''],
            ['LAM_DESCRIPTION', '', '', ''],
            ['LAM_ID', '', '', ''],
            ['LAWYER_ATTORNEY_ADDRESS', 'lawyer', '', ''],
            ['LAWYER_ATTORNEY_CITYSTATEZIP', 'lawyer', '', ''],
            ['LAWYER_ATTORNEY_EMAIL', 'lawyer', '', ''],
            ['LAWYER_ATTORNEY_FAX', 'lawyer', '', ''],
            ['LAWYER_ATTORNEY_NAME', 'lawyer', '', ''],
            ['LAWYER_ATTORNEY_PHONE', 'lawyer', '', ''],
            ['LAWYER_ATTORNEY_SUITE', 'lawyer', '', ''],
            ['LAWYER_OFFICE_LOGO', 'lawyer', '', ''],
            ['LAWYER_OFFICE_NAME', 'lawyer', '', ''],
            ['LAWYER_SIGNATURE', 'lawyer', '', ''],
            ['LEAD', '', '', ''],
            ['MAKE', '', '', ''],
            ['MARITAL_STATUS', '', '', ''],
            ['MEETING_CREDITOR_DATE', '', '', ''],
            ['MEETING_CREDITOR_DESCRIPTION', '', '', ''],
            ['MEETING_CREDITOR_ID', '', '', ''],
            ['MEETING_ROOM', '', '', ''],
            ['MEETING_TIME', '', '', ''],
            ['MODEL', '', '', ''],
            ['NOTES', '', '', ''],
            ['NUMBER_OF_VEHICLES', '', '', ''],
            ['OPPOSING_ATTORNEY_EMAIL', '', '', ''],
            ['OPPOSING_ATTORNEY_FAX', '', '', ''],
            ['OPPOSING_ATTORNEY_FIRM', '', '', ''],
            ['OPPOSING_ATTORNEY_NAME', '', '', ''],
            ['OPPOSING_ATTORNEY_PHONE', '', '', ''],
            ['OTHER_INFO', '', '', ''],
            ['PARALEGAL_ADDRESS', '', '', ''],
            ['PARALEGAL_CITY_STATE_ZIP', '', '', ''],
            ['PARALEGAL_EMAIL', '', '', ''],
            ['PARALEGAL_ID', '', '', ''],
            ['PARALEGAL_NAME', '', '', ''],
            ['PARALEGAL_PHONE_NUMBER', '', '', ''],
            ['PARALEGAL_SUITE', '', '', ''],
            ['PASSENGERS', '', '', ''],
            ['PAYMENT', '', '', ''],
            ['PHONE_NUMBER', '', '', ''],
            ['PHOTOS_TAKEN', '', '', ''],
            ['PLAN_PAYMENT', '', '', ''],
            ['PRE_CONFERENCE', '', '', ''],
            ['PRE_MOTIONS', '', '', ''],
            ['PROPERTY_ADDRESS', '', '', ''],
            ['REGISTERED_OWNER', '', '', ''],
            ['SCHEDULES', '', '', ''],
            ['SECOND_DOWN_PAYMENT', '', '', ''],
            ['SIGNING_DATE', '', '', ''],
            ['SPECIAL_NOTES', '', '', ''],
            ['SSN', '', '', ''],
            ['STAT_CONFERENCE', '', '', ''],
            ['STRIPPING_DATE', '', '', ''],
            ['STRIPPING_PLACE', '', '', ''],
            ['STRIPPING_TIME', '', '', ''],
            ['TAX_SENT_DEC', '', '', ''],
            ['TAX_SENT_NA', '', '', ''],
            ['TAX_SENT_YES', '', '', ''],
            ['TIME_OF_LOSS', '', '', ''],
            ['TRIAL_DATE', '', '', ''],
            ['TRIP_PURPOSE', '', '', ''],
            ['TRUSTEE_ADDRESS', '', '', ''],
            ['TRUSTEE_CITY_STATE_ZIP', '', '', ''],
            ['TRUSTEE_DOC_REQ', '', '', ''],
            ['TRUSTEE_DOC_TYPE', '', '', ''],
            ['TRUSTEE_EMAIL1', '', '', ''],
            ['TRUSTEE_EMAIL2', '', '', ''],
            ['TRUSTEE_FAX_NUMBER', '', '', ''],
            ['TRUSTEE_ID', '', '', ''],
            ['TRUSTEE_NAME', '', '', ''],
            ['TRUSTEE_PHONE_NUMBER', '', '', ''],
            ['TRUSTEE_SUITE', '', '', ''],
            ['VEHICLE', '', '', ''],
            ['VEHICLE_LICENCSE_NO', '', '', ''],
            ['WEATHER', '', '', ''],
            ['YEAR', '', '', ''],
        ];
        
        foreach ($emailVariables as [$variable_name, $variable_type, $table_name, $table_field_name]) {
            DB::table('email_variables')->insert([
                'variable_name'    => $variable_name,
                'variable_type'    => $variable_type,
                'table_name'       => $table_name,
                'table_field_name' => $table_field_name,
            ]);
        }
    }
}
